
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;



contract gameObject  {
    
   

    struct gameObject {
        string objectName;
        address objectAddress;
        uint objectDefence;
    }

    gameObject[] objectArr;

    mapping (address => gameObject) ObjAddr;

    function createObject ( string name, address addr, uint defence ) public {
        
        tvm.accept();
        objectArr.push( gameObject (name, addr, defence ));

    } 






}

