
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "gameObject.sol";

contract Station is gameObject {
   
     struct Station {
        string name;
        address stationAddress;
        uint defenseStation;
    }
    
    struct WarUnit {
        uint attack;
        uint defence;
    }

    WarUnit[] unitArr;
    Station[] stationArr;
    mapping (string=>address) statAddress;

    function createStation (uint defence, string name) public {
        tvm.accept();
        stationArr.push (Station (name, address(this), defence));
        statAddress[name] = address(this);


    }

    function createWarUnit (uint attack, uint defence) internal {
        tvm.accept();
        unitArr.push (WarUnit (attack, defence));


    } 



    constructor() public {
        // Check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        
        require(msg.pubkey() == tvm.pubkey(), 102);
       
        tvm.accept();

        
    }

    
}
